package ru.javaprojects.thinkinginjava.chapter12.exercise4_8_28;

public class Main {
    public static void main(String[] args) {
        throw new MyException("in main");
    }
}
